"""Regiones editoriales EOM → códigos ISO de países para pintar el mapa."""

from __future__ import annotations

# Conjuntos ISO 3166-1 alpha-3 por macro-región
EUROPE = frozenset(
    {
        "ALB",
        "AND",
        "AUT",
        "BLR",
        "BEL",
        "BIH",
        "BGR",
        "HRV",
        "CYP",
        "CZE",
        "DNK",
        "EST",
        "FIN",
        "FRA",
        "DEU",
        "GRC",
        "HUN",
        "ISL",
        "IRL",
        "ITA",
        "XKX",
        "LVA",
        "LIE",
        "LTU",
        "LUX",
        "MLT",
        "MDA",
        "MCO",
        "MNE",
        "NLD",
        "MKD",
        "NOR",
        "POL",
        "PRT",
        "ROU",
        "SMR",
        "SRB",
        "SVK",
        "SVN",
        "ESP",
        "SWE",
        "CHE",
        "UKR",
        "GBR",
        "VAT",
        "GIB",
        "IMN",
        "JEY",
        "GGY",
    }
)

LATIN_AMERICA = frozenset(
    {
        "ARG",
        "BOL",
        "BRA",
        "CHL",
        "COL",
        "CRI",
        "CUB",
        "DOM",
        "ECU",
        "SLV",
        "GTM",
        "GUY",
        "HTI",
        "HND",
        "MEX",
        "NIC",
        "PAN",
        "PRY",
        "PER",
        "SUR",
        "URY",
        "VEN",
        "BLZ",
        "JAM",
        "TTO",
        "BRB",
        "BHS",
        "GRD",
        "DMA",
        "ATG",
        "GUF",
        "GUY",
        "PRI",
    }
)

NORTH_AMERICA = frozenset({"USA", "CAN", "MEX", "GRL", "BMU", "SPM"})

SUBSAHARAN_AFRICA = frozenset(
    {
        "AGO",
        "BEN",
        "BWA",
        "BFA",
        "BDI",
        "CPV",
        "CMR",
        "CAF",
        "TCD",
        "COM",
        "COG",
        "COD",
        "CIV",
        "DJI",
        "GNQ",
        "ERI",
        "ETH",
        "GAB",
        "GMB",
        "GHA",
        "GIN",
        "GNB",
        "KEN",
        "LSO",
        "LBR",
        "MDG",
        "MWI",
        "MLI",
        "MRT",
        "MUS",
        "MOZ",
        "NAM",
        "NER",
        "NGA",
        "RWA",
        "STP",
        "SEN",
        "SYC",
        "SLE",
        "SOM",
        "ZAF",
        "SSD",
        "SDN",
        "SWZ",
        "TZA",
        "TGO",
        "UGA",
        "ZMB",
        "ZWE",
        "ESH",
    }
)

MENA = frozenset(
    {
        "DZA",
        "BHR",
        "EGY",
        "IRN",
        "IRQ",
        "ISR",
        "JOR",
        "KWT",
        "LBN",
        "LBY",
        "MAR",
        "OMN",
        "PSE",
        "QAT",
        "SAU",
        "SYR",
        "TUN",
        "TUR",
        "ARE",
        "YEM",
    }
)

MAGREB_NEAR_EAST = frozenset(
    {
        "DZA",
        "EGY",
        "LBY",
        "MAR",
        "MRT",
        "TUN",
        "ESH",
        "ISR",
        "JOR",
        "LBN",
        "PSE",
        "SYR",
        "TUR",
        "IRQ",
        "IRN",
    }
)

ASIA_PACIFIC = frozenset(
    {
        "AFG",
        "ARM",
        "AZE",
        "BGD",
        "BTN",
        "BRN",
        "KHM",
        "CHN",
        "GEO",
        "HKG",
        "IND",
        "IDN",
        "JPN",
        "KAZ",
        "PRK",
        "KOR",
        "KGZ",
        "LAO",
        "MYS",
        "MDV",
        "MNG",
        "MMR",
        "NPL",
        "NZL",
        "PAK",
        "PHL",
        "SGP",
        "LKA",
        "TWN",
        "TJK",
        "THA",
        "TLS",
        "TKM",
        "UZB",
        "VNM",
        "AUS",
        "FJI",
        "PNG",
        "SLB",
        "VUT",
        "WSM",
        "TON",
        "KIR",
        "MHL",
        "FSM",
        "PLW",
        "NRU",
        "TUV",
        "NCL",
    }
)

CENTRAL_ASIA = frozenset(
    {"KAZ", "UZB", "TKM", "TJK", "KGZ", "AFG", "MNG"},
)

KURDISTAN_AREA = frozenset({"IRQ", "IRN", "TUR", "SYR"})

# slug o nombre normalizado de lugar editorial → conjunto ISO
REGION_TO_ISO: dict[str, frozenset[str]] = {
    "europa": EUROPE,
    "america-latina": LATIN_AMERICA,
    "america-del-norte": NORTH_AMERICA,
    "africa-subsahariana": SUBSAHARAN_AFRICA,
    "oriente-medio-y-norte-de-africa": MENA,
    "oriente-proximo-y-magreb": MAGREB_NEAR_EAST,
    "asia-pacifico": ASIA_PACIFIC,
    "asia-central": CENTRAL_ASIA,
    "kurdistán": KURDISTAN_AREA,
    "kurdistan": KURDISTAN_AREA,
}

# Lugares globales / geográficos sin representación en mapa coroplético
# Antártida sí tiene ISO (ATA) en Natural Earth; Mundo/polos/ártico editorial no.
NON_MAP_PLACES = frozenset(
    {
        "mundo",
        "artico",
        "arctico",
        "polos",
        "polo-norte",
        "polo-sur",
    }
)
