services:
  db:
    image: pgvector/pgvector:pg16-trixie
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - web-semantic-explorer/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: web-semantic-explorer/backend/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - web-semantic-explorer/.env
    environment:
      - POSTGRES_SERVER=db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: web-semantic-explorer/frontend/Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  app-db-data:
    name: web-semantic-explorer_app-db-data
