services:
  db:
    image: pgvector/pgvector:pg16-trixie
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - web-semantic-explorer/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: web-semantic-explorer/backend/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - hf-cache:/app/huggingface_cache
    env_file:
      - web-semantic-explorer/.env
    environment:
      - POSTGRES_SERVER=db
      - HF_HOME=/app/huggingface_cache
    ports:
      - "8000:8000"
    command:
      - bash
      - "-c"
      - "bash ./scripts/prestart.sh && fastapi run --reload app/main.py"
    develop:
      watch:
        - path: ./web-semantic-explorer/backend/app
          action: sync
          target: /app/web-semantic-explorer/backend/app
        - path: ./web-semantic-explorer/backend/pyproject.toml
          action: rebuild

  frontend:
    build:
      context: .
      dockerfile: web-semantic-explorer/frontend/Dockerfile.dev
      args:
        - VITE_API_URL=http://localhost:8000
    restart: always
    depends_on:
      - backend
    # Mantenemos el puerto 8080 público como pediste, conectado al 5173 de Vite interno
    ports:
      - "8080:5173"
    develop:
      watch:
        - path: ./web-semantic-explorer/frontend/src
          action: sync
          target: /app/frontend/src
        - path: ./web-semantic-explorer/frontend/public
          action: sync
          target: /app/frontend/public
        - path: ./web-semantic-explorer/frontend/package.json
          action: rebuild

volumes:
  app-db-data:
    name: web-semantic-explorer_app-db-data
  hf-cache:
    name: web-semantic-explorer_hf-cache
