// This file is auto-generated by @hey-api/openapi-ts

export const ArticleCommentPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        author_name: {
            type: 'string',
            title: 'Author Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        is_own: {
            type: 'boolean',
            title: 'Is Own',
            default: false
        }
    },
    type: 'object',
    required: ['id', 'content', 'author_name', 'created_at'],
    title: 'ArticleCommentPublic'
} as const;

export const ArticleDetailPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        excerpt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excerpt'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date'
        },
        paywalled: {
            type: 'boolean',
            title: 'Paywalled'
        },
        authors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Authors'
        },
        categories: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Categories'
        },
        places: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Places'
        },
        comments: {
            items: {
                '$ref': '#/components/schemas/ArticleCommentPublic'
            },
            type: 'array',
            title: 'Comments'
        },
        average_rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average Rating'
        },
        ratings_count: {
            type: 'integer',
            title: 'Ratings Count'
        },
        user_rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Rating'
        },
        is_favorited: {
            type: 'boolean',
            title: 'Is Favorited',
            default: false
        },
        user_note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Note'
        },
        user_note_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Note Updated At'
        },
        follow_targets: {
            items: {
                '$ref': '#/components/schemas/FollowTargetPublic'
            },
            type: 'array',
            title: 'Follow Targets'
        }
    },
    type: 'object',
    required: ['id', 'title', 'url', 'excerpt', 'image_url', 'date', 'paywalled', 'authors', 'categories', 'places', 'comments', 'average_rating', 'ratings_count'],
    title: 'ArticleDetailPublic'
} as const;

export const ArticleMetadataFiltersSchema = {
    properties: {
        place: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Place',
            description: 'Filtra por nombre o slug de Place'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category',
            description: 'Filtra por nombre de Category'
        },
        author: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author',
            description: 'Nombre exacto de Author (filtro duro, desde lista)'
        },
        year_start: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Year Start',
            description: 'Año mínimo de publicación (inclusive)'
        },
        year_end: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Year End',
            description: 'Año máximo de publicación (inclusive)'
        }
    },
    type: 'object',
    title: 'ArticleMetadataFilters',
    description: 'Filtros opcionales de metadatos para búsqueda y expansión del grafo.'
} as const;

export const ArticleSearchResultSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        excerpt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excerpt'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date'
        },
        paywalled: {
            type: 'boolean',
            title: 'Paywalled'
        },
        similarity: {
            type: 'number',
            title: 'Similarity'
        },
        authors: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Authors'
        }
    },
    type: 'object',
    required: ['id', 'title', 'url', 'excerpt', 'image_url', 'date', 'paywalled', 'similarity'],
    title: 'ArticleSearchResult'
} as const;

export const AuthorOptionSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'AuthorOption'
} as const;

export const AuthorsListResponseSchema = {
    properties: {
        authors: {
            items: {
                '$ref': '#/components/schemas/AuthorOption'
            },
            type: 'array',
            title: 'Authors'
        }
    },
    type: 'object',
    required: ['authors'],
    title: 'AuthorsListResponse'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CommentCreateSchema = {
    properties: {
        content: {
            type: 'string',
            maxLength: 4000,
            minLength: 1,
            title: 'Content'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'CommentCreate'
} as const;

export const CommentPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        article_id: {
            type: 'integer',
            title: 'Article Id'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        author_name: {
            type: 'string',
            title: 'Author Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        is_own: {
            type: 'boolean',
            title: 'Is Own',
            default: false
        }
    },
    type: 'object',
    required: ['id', 'article_id', 'content', 'author_name', 'created_at'],
    title: 'CommentPublic'
} as const;

export const CommentUpdateSchema = {
    properties: {
        content: {
            type: 'string',
            maxLength: 4000,
            minLength: 1,
            title: 'Content'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'CommentUpdate'
} as const;

export const ExpandRequestSchema = {
    properties: {
        source_article_id: {
            type: 'integer',
            title: 'Source Article Id'
        },
        existing_node_ids: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Existing Node Ids'
        },
        filters: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ArticleMetadataFilters'
                },
                {
                    type: 'null'
                }
            ]
        },
        seed_queries: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Seed Queries',
            description: 'Textos de nodos input upstream (semillas de la isla).'
        },
        context_article_ids: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Context Article Ids',
            description: 'Ids de artículos en la cadena de ancestros (walk-up).'
        }
    },
    type: 'object',
    required: ['source_article_id', 'existing_node_ids'],
    title: 'ExpandRequest'
} as const;

export const ExpandResponseSchema = {
    properties: {
        new_nodes: {
            items: {
                '$ref': '#/components/schemas/GraphNode'
            },
            type: 'array',
            title: 'New Nodes'
        },
        new_edges: {
            items: {
                '$ref': '#/components/schemas/GraphEdge'
            },
            type: 'array',
            title: 'New Edges'
        }
    },
    type: 'object',
    required: ['new_nodes', 'new_edges'],
    title: 'ExpandResponse'
} as const;

export const FavoriteArticlePublicSchema = {
    properties: {
        article_id: {
            type: 'integer',
            title: 'Article Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        excerpt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excerpt'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        authors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Authors'
        },
        categories: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Categories'
        },
        places: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Places'
        },
        average_rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average Rating'
        },
        user_rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Rating'
        },
        favorited_at: {
            type: 'string',
            format: 'date-time',
            title: 'Favorited At'
        }
    },
    type: 'object',
    required: ['article_id', 'title', 'excerpt', 'image_url', 'url', 'authors', 'categories', 'favorited_at'],
    title: 'FavoriteArticlePublic'
} as const;

export const FavoriteStatusPublicSchema = {
    properties: {
        article_id: {
            type: 'integer',
            title: 'Article Id'
        },
        is_favorited: {
            type: 'boolean',
            title: 'Is Favorited'
        }
    },
    type: 'object',
    required: ['article_id', 'is_favorited'],
    title: 'FavoriteStatusPublic'
} as const;

export const FavoritesListPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FavoriteArticlePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'FavoritesListPublic'
} as const;

export const FollowCreateSchema = {
    properties: {
        target_type: {
            type: 'string',
            maxLength: 20,
            title: 'Target Type'
        },
        target_id: {
            type: 'integer',
            minimum: 1,
            title: 'Target Id'
        }
    },
    type: 'object',
    required: ['target_type', 'target_id'],
    title: 'FollowCreate'
} as const;

export const FollowPublicSchema = {
    properties: {
        target_type: {
            type: 'string',
            title: 'Target Type'
        },
        target_id: {
            type: 'integer',
            title: 'Target Id'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['target_type', 'target_id', 'label', 'created_at'],
    title: 'FollowPublic'
} as const;

export const FollowStatusPublicSchema = {
    properties: {
        target_type: {
            type: 'string',
            title: 'Target Type'
        },
        target_id: {
            type: 'integer',
            title: 'Target Id'
        },
        is_following: {
            type: 'boolean',
            title: 'Is Following'
        }
    },
    type: 'object',
    required: ['target_type', 'target_id', 'is_following'],
    title: 'FollowStatusPublic'
} as const;

export const FollowTargetPublicSchema = {
    properties: {
        target_type: {
            type: 'string',
            title: 'Target Type'
        },
        target_id: {
            type: 'integer',
            title: 'Target Id'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        is_following: {
            type: 'boolean',
            title: 'Is Following',
            default: false
        }
    },
    type: 'object',
    required: ['target_type', 'target_id', 'label'],
    title: 'FollowTargetPublic'
} as const;

export const FollowsListPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FollowPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'FollowsListPublic'
} as const;

export const GraphEdgeSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        source: {
            type: 'string',
            title: 'Source'
        },
        target: {
            type: 'string',
            title: 'Target'
        },
        similarity: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Similarity'
        }
    },
    type: 'object',
    required: ['id', 'source', 'target'],
    title: 'GraphEdge'
} as const;

export const GraphNodeSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        data: {
            '$ref': '#/components/schemas/ArticleSearchResult'
        }
    },
    type: 'object',
    required: ['id', 'data'],
    title: 'GraphNode'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HeatmapEntrySchema = {
    properties: {
        place_id: {
            type: 'integer',
            title: 'Place Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        country_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Code'
        },
        map_country_codes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Map Country Codes',
            default: []
        },
        article_count: {
            type: 'integer',
            title: 'Article Count'
        }
    },
    type: 'object',
    required: ['place_id', 'name', 'article_count'],
    title: 'HeatmapEntry'
} as const;

export const HeatmapResponseSchema = {
    properties: {
        total_articles: {
            type: 'integer',
            title: 'Total Articles'
        },
        entries: {
            items: {
                '$ref': '#/components/schemas/HeatmapEntry'
            },
            type: 'array',
            title: 'Entries'
        }
    },
    type: 'object',
    required: ['total_articles'],
    title: 'HeatmapResponse'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NotePublicSchema = {
    properties: {
        article_id: {
            type: 'integer',
            title: 'Article Id'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['article_id', 'content'],
    title: 'NotePublic'
} as const;

export const NoteUpsertSchema = {
    properties: {
        content: {
            type: 'string',
            maxLength: 8000,
            title: 'Content'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'NoteUpsert'
} as const;

export const PlaceArticlePreviewSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        excerpt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excerpt'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date'
        },
        average_rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average Rating'
        },
        ratings_count: {
            type: 'integer',
            title: 'Ratings Count',
            default: 0
        }
    },
    type: 'object',
    required: ['id'],
    title: 'PlaceArticlePreview'
} as const;

export const PlacePreviewResponseSchema = {
    properties: {
        place_id: {
            type: 'integer',
            title: 'Place Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        article_count: {
            type: 'integer',
            title: 'Article Count'
        },
        top_rated: {
            items: {
                '$ref': '#/components/schemas/PlaceArticlePreview'
            },
            type: 'array',
            title: 'Top Rated'
        }
    },
    type: 'object',
    required: ['place_id', 'name', 'article_count'],
    title: 'PlacePreviewResponse'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RatingSummaryPublicSchema = {
    properties: {
        article_id: {
            type: 'integer',
            title: 'Article Id'
        },
        average_rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average Rating'
        },
        ratings_count: {
            type: 'integer',
            title: 'Ratings Count'
        },
        user_rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Rating'
        }
    },
    type: 'object',
    required: ['article_id', 'average_rating', 'ratings_count'],
    title: 'RatingSummaryPublic'
} as const;

export const RatingUpsertSchema = {
    properties: {
        value: {
            type: 'number',
            maximum: 5,
            minimum: 0.5,
            title: 'Value'
        }
    },
    type: 'object',
    required: ['value'],
    title: 'RatingUpsert'
} as const;

export const SearchResponseSchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        },
        results: {
            items: {
                '$ref': '#/components/schemas/ArticleSearchResult'
            },
            type: 'array',
            title: 'Results'
        }
    },
    type: 'object',
    required: ['query', 'results'],
    title: 'SearchResponse'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        color_theme: {
            type: 'string',
            title: 'Color Theme',
            default: 'eom'
        },
        appearance_mode: {
            type: 'string',
            title: 'Appearance Mode',
            default: 'system'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        color_theme: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Theme'
        },
        appearance_mode: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 16
                },
                {
                    type: 'null'
                }
            ],
            title: 'Appearance Mode'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WorkspaceCreateSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        schema_version: {
            type: 'integer',
            title: 'Schema Version',
            default: 1
        },
        graph: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/WorkspaceGraphSnapshotPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['name'],
    title: 'WorkspaceCreate'
} as const;

export const WorkspaceGraphSnapshotPublicSchema = {
    properties: {
        nodes: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Nodes'
        },
        edges: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Edges'
        },
        viewport: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Viewport'
        }
    },
    type: 'object',
    title: 'WorkspaceGraphSnapshotPublic'
} as const;

export const WorkspacePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        schema_version: {
            type: 'integer',
            title: 'Schema Version'
        },
        graph: {
            '$ref': '#/components/schemas/WorkspaceGraphSnapshotPublic'
        },
        server_revision: {
            type: 'string',
            format: 'uuid',
            title: 'Server Revision'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'schema_version', 'graph', 'server_revision', 'created_at', 'updated_at'],
    title: 'WorkspacePublic'
} as const;

export const WorkspaceSyncItemSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        schema_version: {
            type: 'integer',
            title: 'Schema Version',
            default: 1
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        graph: {
            '$ref': '#/components/schemas/WorkspaceGraphSnapshotPublic'
        },
        server_revision: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Server Revision'
        }
    },
    type: 'object',
    required: ['id', 'name', 'updated_at', 'graph'],
    title: 'WorkspaceSyncItem'
} as const;

export const WorkspaceSyncPayloadSchema = {
    properties: {
        schema_version: {
            type: 'integer',
            title: 'Schema Version',
            default: 1
        },
        active_workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Active Workspace Id'
        },
        workspaces: {
            items: {
                '$ref': '#/components/schemas/WorkspaceSyncItem'
            },
            type: 'array',
            title: 'Workspaces'
        }
    },
    type: 'object',
    required: ['active_workspace_id', 'workspaces'],
    title: 'WorkspaceSyncPayload'
} as const;

export const WorkspaceSyncResponseSchema = {
    properties: {
        schema_version: {
            type: 'integer',
            title: 'Schema Version'
        },
        active_workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Active Workspace Id'
        },
        workspaces: {
            items: {
                '$ref': '#/components/schemas/WorkspacePublic'
            },
            type: 'array',
            title: 'Workspaces'
        }
    },
    type: 'object',
    required: ['schema_version', 'active_workspace_id', 'workspaces'],
    title: 'WorkspaceSyncResponse'
} as const;

export const WorkspaceUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        schema_version: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Schema Version'
        },
        graph: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/WorkspaceGraphSnapshotPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        server_revision: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Server Revision'
        }
    },
    type: 'object',
    title: 'WorkspaceUpdate'
} as const;

export const WorkspacesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkspacePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkspacesPublic'
} as const;