// This file is auto-generated by @hey-api/openapi-ts

export type ArticleCommentPublic = {
    id: number;
    content: string;
    author_name: string;
    created_at: string;
    is_own?: boolean;
};

export type ArticleDetailPublic = {
    id: number;
    title: (string | null);
    url: string;
    excerpt: (string | null);
    image_url: (string | null);
    date: (string | null);
    paywalled: boolean;
    authors: Array<(string)>;
    categories: Array<(string)>;
    places: Array<(string)>;
    comments: Array<ArticleCommentPublic>;
    average_rating: (number | null);
    ratings_count: number;
    user_rating?: (number | null);
    is_favorited?: boolean;
    user_note?: (string | null);
    user_note_updated_at?: (string | null);
    follow_targets?: Array<FollowTargetPublic>;
};

/**
 * Filtros opcionales de metadatos para búsqueda y expansión del grafo.
 */
export type ArticleMetadataFilters = {
    /**
     * Filtra por nombre o slug de Place
     */
    place?: (string | null);
    /**
     * Filtra por nombre de Category
     */
    category?: (string | null);
    /**
     * Nombre exacto de Author (filtro duro, desde lista)
     */
    author?: (string | null);
    /**
     * Año mínimo de publicación (inclusive)
     */
    year_start?: (number | null);
    /**
     * Año máximo de publicación (inclusive)
     */
    year_end?: (number | null);
};

export type ArticleSearchResult = {
    id: number;
    title: (string | null);
    url: string;
    excerpt: (string | null);
    image_url: (string | null);
    date: (string | null);
    paywalled: boolean;
    similarity: number;
    authors?: (Array<(string)> | null);
};

export type AuthorOption = {
    name: string;
};

export type AuthorsListResponse = {
    authors: Array<AuthorOption>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CommentCreate = {
    content: string;
};

export type CommentPublic = {
    id: number;
    article_id: number;
    content: string;
    author_name: string;
    created_at: string;
    updated_at?: (string | null);
    is_own?: boolean;
};

export type CommentUpdate = {
    content: string;
};

export type ExpandRequest = {
    source_article_id: number;
    existing_node_ids: Array<(number)>;
    filters?: (ArticleMetadataFilters | null);
    /**
     * Textos de nodos input upstream (semillas de la isla).
     */
    seed_queries?: Array<(string)>;
    /**
     * Ids de artículos en la cadena de ancestros (walk-up).
     */
    context_article_ids?: Array<(number)>;
};

export type ExpandResponse = {
    new_nodes: Array<GraphNode>;
    new_edges: Array<GraphEdge>;
};

export type FavoriteArticlePublic = {
    article_id: number;
    title: (string | null);
    excerpt: (string | null);
    image_url: (string | null);
    url: string;
    authors: Array<(string)>;
    categories: Array<(string)>;
    places?: Array<(string)>;
    average_rating?: (number | null);
    user_rating?: (number | null);
    favorited_at: string;
};

export type FavoritesListPublic = {
    data: Array<FavoriteArticlePublic>;
    count: number;
};

export type FavoriteStatusPublic = {
    article_id: number;
    is_favorited: boolean;
};

export type FollowCreate = {
    target_type: string;
    target_id: number;
};

export type FollowPublic = {
    target_type: string;
    target_id: number;
    label: string;
    created_at: string;
};

export type FollowsListPublic = {
    data: Array<FollowPublic>;
    count: number;
};

export type FollowStatusPublic = {
    target_type: string;
    target_id: number;
    is_following: boolean;
};

export type FollowTargetPublic = {
    target_type: string;
    target_id: number;
    label: string;
    is_following?: boolean;
};

export type GraphEdge = {
    id: string;
    source: string;
    target: string;
    similarity?: (number | null);
};

export type GraphNode = {
    id: string;
    data: ArticleSearchResult;
};

export type HeatmapEntry = {
    place_id: number;
    name: string;
    slug?: (string | null);
    country_code?: (string | null);
    map_country_codes?: Array<(string)>;
    article_count: number;
};

export type HeatmapResponse = {
    total_articles: number;
    entries?: Array<HeatmapEntry>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotePublic = {
    article_id: number;
    content: string;
    updated_at?: (string | null);
};

export type NoteUpsert = {
    content: string;
};

export type PlaceArticlePreview = {
    id: number;
    title?: (string | null);
    excerpt?: (string | null);
    image_url?: (string | null);
    date?: (string | null);
    average_rating?: (number | null);
    ratings_count?: number;
};

export type PlacePreviewResponse = {
    place_id: number;
    name: string;
    article_count: number;
    top_rated?: Array<PlaceArticlePreview>;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RatingSummaryPublic = {
    article_id: number;
    average_rating: (number | null);
    ratings_count: number;
    user_rating?: (number | null);
};

export type RatingUpsert = {
    value: number;
};

export type SearchResponse = {
    query: string;
    results: Array<ArticleSearchResult>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    color_theme?: string;
    appearance_mode?: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    color_theme?: (string | null);
    appearance_mode?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WorkspaceCreate = {
    id?: (string | null);
    name: string;
    schema_version?: number;
    graph?: (WorkspaceGraphSnapshotPublic | null);
};

export type WorkspaceGraphSnapshotPublic = {
    nodes?: Array<{
        [key: string]: unknown;
    }>;
    edges?: Array<{
        [key: string]: unknown;
    }>;
    viewport?: ({
    [key: string]: unknown;
} | null);
};

export type WorkspacePublic = {
    id: string;
    name: string;
    schema_version: number;
    graph: WorkspaceGraphSnapshotPublic;
    server_revision: string;
    created_at: string;
    updated_at: string;
};

export type WorkspacesPublic = {
    data: Array<WorkspacePublic>;
    count: number;
};

export type WorkspaceSyncItem = {
    id: string;
    name: string;
    schema_version?: number;
    updated_at: string;
    graph: WorkspaceGraphSnapshotPublic;
    server_revision?: (string | null);
};

export type WorkspaceSyncPayload = {
    schema_version?: number;
    active_workspace_id: string;
    workspaces: Array<WorkspaceSyncItem>;
};

export type WorkspaceSyncResponse = {
    schema_version: number;
    active_workspace_id: string;
    workspaces: Array<WorkspacePublic>;
};

export type WorkspaceUpdate = {
    name?: (string | null);
    schema_version?: (number | null);
    graph?: (WorkspaceGraphSnapshotPublic | null);
    server_revision?: (string | null);
};

export type ArticlesGetArticleDetailData = {
    articleId: number;
};

export type ArticlesGetArticleDetailResponse = (ArticleDetailPublic);

export type ArticlesToggleArticleFavoriteData = {
    articleId: number;
};

export type ArticlesToggleArticleFavoriteResponse = (FavoriteStatusPublic);

export type ArticlesRemoveArticleFavoriteData = {
    articleId: number;
};

export type ArticlesRemoveArticleFavoriteResponse = (FavoriteStatusPublic);

export type ArticlesUpsertArticleRatingData = {
    articleId: number;
    requestBody: RatingUpsert;
};

export type ArticlesUpsertArticleRatingResponse = (RatingSummaryPublic);

export type ArticlesGetArticleRatingSummaryData = {
    articleId: number;
};

export type ArticlesGetArticleRatingSummaryResponse = (RatingSummaryPublic);

export type ArticlesListArticleCommentsData = {
    articleId: number;
};

export type ArticlesListArticleCommentsResponse = (Array<CommentPublic>);

export type ArticlesCreateArticleCommentData = {
    articleId: number;
    requestBody: CommentCreate;
};

export type ArticlesCreateArticleCommentResponse = (CommentPublic);

export type ArticlesGetArticleNoteData = {
    articleId: number;
};

export type ArticlesGetArticleNoteResponse = (NotePublic);

export type ArticlesUpsertArticleNoteData = {
    articleId: number;
    requestBody: NoteUpsert;
};

export type ArticlesUpsertArticleNoteResponse = (NotePublic);

export type CommentsUpdateCommentData = {
    commentId: number;
    requestBody: CommentUpdate;
};

export type CommentsUpdateCommentResponse = (CommentPublic);

export type CommentsDeleteCommentData = {
    commentId: number;
};

export type CommentsDeleteCommentResponse = (void);

export type FavoritesListFavoritesResponse = (FavoritesListPublic);

export type FavoritesAddFavoriteData = {
    articleId: number;
};

export type FavoritesAddFavoriteResponse = (FavoriteStatusPublic);

export type FavoritesDeleteFavoriteData = {
    articleId: number;
};

export type FavoritesDeleteFavoriteResponse = (FavoriteStatusPublic);

export type FollowsListFollowsResponse = (FollowsListPublic);

export type FollowsFollowTargetData = {
    requestBody: FollowCreate;
};

export type FollowsFollowTargetResponse = (FollowStatusPublic);

export type FollowsUnfollowTargetData = {
    targetId: number;
    targetType: string;
};

export type FollowsUnfollowTargetResponse = (FollowStatusPublic);

export type GraphExpandGraphRouteData = {
    limit?: number;
    requestBody: ExpandRequest;
    threshold?: number;
};

export type GraphExpandGraphRouteResponse = (ExpandResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RatingsCreateOrUpdateRatingData = {
    /**
     * ID del artículo
     */
    articleId: number;
    requestBody: RatingUpsert;
};

export type RatingsCreateOrUpdateRatingResponse = (RatingSummaryPublic);

export type RatingsGetRatingAverageData = {
    /**
     * ID del artículo
     */
    articleId: number;
};

export type RatingsGetRatingAverageResponse = (RatingSummaryPublic);

export type SearchSearchArticlesData = {
    /**
     * Filtra por nombre de Author
     */
    author?: (string | null);
    /**
     * Filtra por nombre de Category
     */
    category?: (string | null);
    /**
     * Ids de artículos ancestros del input para mezclar contexto
     */
    contextArticleIds?: (Array<(number)> | null);
    /**
     * Número máximo de artículos a devolver
     */
    limit?: number;
    /**
     * Filtra por nombre o slug de Place
     */
    place?: (string | null);
    /**
     * Texto libre a buscar en los artículos
     */
    q: string;
    /**
     * Consultas de nodos input upstream (repetir param para varias)
     */
    seedQueries?: (Array<(string)> | null);
    /**
     * Año máximo de publicación (inclusive)
     */
    yearEnd?: (number | null);
    /**
     * Año mínimo de publicación (inclusive)
     */
    yearStart?: (number | null);
};

export type SearchSearchArticlesResponse = (SearchResponse);

export type StatsGetHeatmapResponse = (HeatmapResponse);

export type StatsGetPlacePreviewData = {
    limit?: number;
    placeId: number;
};

export type StatsGetPlacePreviewResponse = (PlacePreviewResponse);

export type TaxonomyListAuthorsResponse = (AuthorsListResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WorkspacesListWorkspacesResponse = (WorkspacesPublic);

export type WorkspacesCreateWorkspaceData = {
    requestBody: WorkspaceCreate;
};

export type WorkspacesCreateWorkspaceResponse = (WorkspacePublic);

export type WorkspacesGetWorkspaceSyncResponse = (WorkspaceSyncResponse);

export type WorkspacesPutWorkspaceSyncData = {
    requestBody: WorkspaceSyncPayload;
};

export type WorkspacesPutWorkspaceSyncResponse = (WorkspaceSyncResponse);

export type WorkspacesGetWorkspaceData = {
    workspaceId: string;
};

export type WorkspacesGetWorkspaceResponse = (WorkspacePublic);

export type WorkspacesUpdateWorkspaceData = {
    requestBody: WorkspaceUpdate;
    workspaceId: string;
};

export type WorkspacesUpdateWorkspaceResponse = (WorkspacePublic);

export type WorkspacesDeleteWorkspaceData = {
    workspaceId: string;
};

export type WorkspacesDeleteWorkspaceResponse = ({
    [key: string]: (string);
});